<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <LangVersion>latest</LangVersion>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Nullable>disable</Nullable>
    <OutputPath>..\..\build\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>

  <PropertyGroup>
    <BepInExCorePath Condition="'$(BepInExCorePath)' == ''">..\..\..\..\core</BepInExCorePath>
    <GameManagedPath Condition="'$(GameManagedPath)' == ''">$(PEAKManagedPath)</GameManagedPath>
    <GameManagedPath Condition="'$(GameManagedPath)' == ''">F:\Video Games\SteamLibrary\steamapps\common\PEAK\PEAK_Data\Managed</GameManagedPath>
  </PropertyGroup>

  <ItemDefinitionGroup>
    <Reference>
      <Private>false</Private>
    </Reference>
  </ItemDefinitionGroup>

  <ItemGroup>
    <Reference Include="BepInEx">
      <HintPath>$(BepInExCorePath)\BepInEx.dll</HintPath>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>$(BepInExCorePath)\0Harmony.dll</HintPath>
    </Reference>
    <Reference Include="Assembly-CSharp">
      <HintPath>$(GameManagedPath)\Assembly-CSharp.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>$(GameManagedPath)\UnityEngine.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(GameManagedPath)\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.PhysicsModule">
      <HintPath>$(GameManagedPath)\UnityEngine.PhysicsModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.ParticleSystemModule">
      <HintPath>$(GameManagedPath)\UnityEngine.ParticleSystemModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.InputLegacyModule">
      <HintPath>$(GameManagedPath)\UnityEngine.InputLegacyModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.IMGUIModule">
      <HintPath>$(GameManagedPath)\UnityEngine.IMGUIModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.TextRenderingModule">
      <HintPath>$(GameManagedPath)\UnityEngine.TextRenderingModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>$(GameManagedPath)\UnityEngine.UI.dll</HintPath>
    </Reference>
    <Reference Include="Unity.TextMeshPro">
      <HintPath>$(GameManagedPath)\Unity.TextMeshPro.dll</HintPath>
    </Reference>
    <Reference Include="PhotonRealtime">
      <HintPath>$(GameManagedPath)\PhotonRealtime.dll</HintPath>
    </Reference>
    <Reference Include="PhotonUnityNetworking">
      <HintPath>$(GameManagedPath)\PhotonUnityNetworking.dll</HintPath>
    </Reference>
    <Reference Include="Photon3Unity3D">
      <HintPath>$(GameManagedPath)\Photon3Unity3D.dll</HintPath>
    </Reference>
    <Reference Include="Newtonsoft.Json">
      <HintPath>$(GameManagedPath)\Newtonsoft.Json.dll</HintPath>
    </Reference>
    <Reference Include="Zorro.Core.Runtime">
      <HintPath>$(GameManagedPath)\Zorro.Core.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="Zorro.UI.Runtime">
      <HintPath>$(GameManagedPath)\Zorro.UI.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="Zorro.PhotonUtility">
      <HintPath>$(GameManagedPath)\Zorro.PhotonUtility.dll</HintPath>
    </Reference>
    <Reference Include="Sirenix.Serialization">
      <HintPath>$(GameManagedPath)\Sirenix.Serialization.dll</HintPath>
    </Reference>
    <Reference Include="Sirenix.Serialization.Config">
      <HintPath>$(GameManagedPath)\Sirenix.Serialization.Config.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
